<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="$rc.contextPath$/resources/bootstrap-3.3.2-dist/favicon.ico">

    <title>How-To? | Technology made easier.</title>

    <!-- Bootstrap core CSS -->
    <link href="$rc.contextPath$/resources/bootstrap-3.3.2-dist/css/bootstrap.min.css" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-check"></span> How-To? | Technology made easier.</a>
        </div>
      </div>
    </nav>

$(bodytemplate)()$


    <div class="container">

      <hr>

      <footer>
        <p>&copy; Xavier CARON 2015</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="$rc.contextPath$/resources/bootstrap-3.3.2-dist/dist/js/bootstrap.min.js"></script>
  </body>
</html>

